### ISSUE TITLE
Crash with QSL 4.0.0 beta 8

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [DawnTeamMC/Artisanat#29]
### What happened?

**MC** 1.19.2
**[QSL](https://modrinth.com/mod/qsl)** 4.0.0 beta 8
**Artisanat** 2.3.0

The game crashes on startup with QSL 4.0.0 beta 8. QSL is a part of Quilt that provides Fabric API, as well as its own tools.

The crash does not happen with QSL 4.0.0 beta 7.

[Quilt](https://quiltmc.org/) is a modloader that natively supports all Fabric mods (e.g. Promenade still works), apart from some very rare exceptions, but since it seems like some change in QSL broke compatibility with your mod, I will understand if that's not something you are willing to fix, since Quilt support isn't officially stated anywhere on the mod page.

**Edit:** QSL 4.0.0 beta 9 is also affected.

### Dawn API version

3.5.0

### Fabric API version

0.59.0

### Relevant log output

```shell
https://gist.github.com/Footage2-Amply-Pounce/fdbb31bcdcde4b1bf8a351edee369716
```

**Comment by Hugman76** [comment]
Yeah it seems like Quilt is creating issues that are not present with Fabric. :D

**Comment by gdude2002** [comment]
I believe the issue here is that you're making use of a block instance before it's even registered, right? You are, of course, free to not support Quilt at all, but it might be worth fixing this regardless - for the sake of avoiding breakages with other parts of the Fabric ecosystem, or potentially Fabric itself in the future.

**Comment by Hugman76** [comment]
I believe I had advantages in registering my features late, but I might change this at some point as I don't even remember what those advantages where. It always worked fine in the past. It would require a huge rework though, and as a freshman I don't know if I will have enough time to refactor all of this...

**Comment by gdude2002** [comment]
Yep, that's all totally fair, just figured I'd point out that it's probably not best practice. o7
